export const sampleProducts = [
    {
        id: 101,
        name: 'لنت ترمز جلو پراید',
        description: 'لنت ترمز با کیفیت بالا برای پراید، مناسب برای استفاده روزمره و عملکرد ایمن.',
        price: 420000,
        discountPrice: 370000,
        stockQuantity: 26,
        status: 'Available',
        SKU: 'CP-PRD-001',
        brand: 'Chinese',
        model: 'Pride',
        categoryId: 1,
        categoryName: 'لنت ترمز',
        partNumber: 'CP-1001',
        manufacturer: 'SuperBrake',
        warranty: '6 ماه',
        isOriginal: false,
        rating: 4.6,
        reviewCount: 42,
        imageUrl: '/logo192.png',
        additionalImages: ['/logo192.png'],
        createdAt: new Date().toISOString(),
    },
    {
        id: 102,
        name: 'فیلتر روغن ایران خودرو',
        description: 'فیلتر روغن استاندارد برای خودروهای ایران‌خودرو با عملکرد بهینه و طول عمر بالا.',
        price: 180000,
        discountPrice: 150000,
        stockQuantity: 44,
        status: 'Available',
        SKU: 'IK-OF-002',
        brand: 'IranKhodro',
        model: 'Dena',
        categoryId: 2,
        categoryName: 'فیلتر روغن',
        partNumber: 'IK-2021',
        manufacturer: 'AutoPlus',
        warranty: '1 سال',
        isOriginal: true,
        rating: 4.8,
        reviewCount: 58,
        imageUrl: '/logo192.png',
        additionalImages: ['/logo192.png'],
        createdAt: new Date().toISOString(),
    },
    {
        id: 103,
        name: 'شمع موتور سایپا',
        description: 'شمع موتور با کیفیت برتر مخصوص موتورهای سایپا جهت احتراق بهتر و مصرف سوخت کمتر.',
        price: 65000,
        stockQuantity: 80,
        status: 'Available',
        SKU: 'SP-SH-003',
        brand: 'Saipa',
        model: 'Tiba',
        categoryId: 3,
        categoryName: 'شمع موتور',
        partNumber: 'SP-3070',
        manufacturer: 'SparkTech',
        warranty: '3 ماه',
        isOriginal: false,
        rating: 4.4,
        reviewCount: 27,
        imageUrl: '/logo192.png',
        additionalImages: ['/logo192.png'],
        createdAt: new Date().toISOString(),
    },
    {
        id: 104,
        name: 'واشر درب سوپاپ ایران خودرو',
        description: 'واشر تیپ بالا برای جلوگیری از نشت روغن و آب در موتور ایران‌خودرو.',
        price: 240000,
        discountPrice: 225000,
        stockQuantity: 12,
        status: 'Available',
        SKU: 'IK-GSK-004',
        brand: 'IranKhodro',
        model: 'Samand',
        categoryId: 4,
        categoryName: 'واشرها',
        partNumber: 'IK-4458',
        manufacturer: 'SealMax',
        warranty: '6 ماه',
        isOriginal: true,
        rating: 4.5,
        reviewCount: 34,
        imageUrl: '/logo192.png',
        additionalImages: ['/logo192.png'],
        createdAt: new Date().toISOString(),
    },
];
export const brandBanners = [
    {
        title: 'لوازم چینی',
        description: 'کالای اقتصادی و با کیفیت برای خودروهای وارداتی و تولید داخل',
        color: 'from-cyan-500 to-blue-600',
        href: '/chinese-parts',
    },
    {
        title: 'لوازم سایپا',
        description: 'قطعات اورجینال و تقویت‌شده برای خودروهای سایپا',
        color: 'from-orange-400 to-red-500',
        href: '/saipa-parts',
    },
    {
        title: 'لوازم ایران‌خودرو',
        description: 'مناسب‌ترین قطعات برای خودروهای ایران‌خودرو با پشتیبانی سریع',
        color: 'from-sky-500 to-indigo-600',
        href: '/irankhodro-parts',
    },
];
export const sampleStats = {
    totalProducts: 1320,
    totalOrders: 280,
    totalRevenue: 112500000,
    totalUsers: 890,
    lowStockProducts: 24,
    pendingOrders: 16,
};
export const sampleOrders = [
    { id: 2101, customer: 'محمد حسینی', totalAmount: '2,300,000', status: 'در حال پردازش' },
    { id: 2102, customer: 'علی رضایی', totalAmount: '1,450,000', status: 'ارسال شده' },
    { id: 2103, customer: 'سارا احمدی', totalAmount: '980,000', status: 'تحویل شده' },
];
export const sampleUsers = [
    { id: 1, firstName: 'مهدی', lastName: 'کاظمی', email: 'mehdi@example.com' },
    { id: 2, firstName: 'فاطمه', lastName: 'نوروزی', email: 'fatemeh@example.com' },
    { id: 3, firstName: 'امیر', lastName: 'جعفری', email: 'amir@example.com' },
];
