// فایل دادههای تستی برای سیستم جستجوی پیشرفته
// تولید شده در ۲۰۲۴-۰۱-۱۵

import type { Product } from '../types';

export const testProducts: Product[] = [
  {
    id: 1,
    name: "لنت ترمز جلو Saipa Pride",
    description: "لنت ترمز با کیفیت بالا برای خودروهای Saipa مدل Pride. این محصول از جنس Metal ساخته شده و دارای گارانتی 1 year میباشد.",
    price: 150000,
    discountPrice: 120000,
    stockQuantity: 50,
    status: "Available",
    SKU: "BRAKE001",
    brand: "سایپا",
    model: "پراید",
    categoryId: 1,
    categoryName: "سیستم ترمز",
    partNumber: "1234-567",
    manufacturer: "Bosch",
    warranty: "1 year",
    isOriginal: true,
    rating: 4.5,
    reviewCount: 24,
    imageUrl: "/uploads/products/product_1.jpg",
    additionalImages: ["/uploads/products/product_1_1.jpg", "/uploads/products/product_1_2.jpg"],
    createdAt: "2024-01-10T10:30:00",
    viewCount: 150,
    favoriteCount: 12,
    isFeatured: true,
    isActive: true,
    sku: "BRAKE001",
    compatibleCars: "Saipa Pride, Saipa Tiba",
    material: "Metal",
    updatedAt: "2024-01-12T14:20:00",
    lastViewedAt: "2024-01-14T09:15:00"
  },
  {
    id: 2,
    name: "فیلتر هوا کاغذی IranKhodro 206",
    description: "فیلتر هوا با کیفیت بالا برای خودروهای IranKhodro مدل 206. این محصول از جنس Paper ساخته شده و دارای گارانتی 6 months میباشد.",
    price: 80000,
    discountPrice: 65000,
    stockQuantity: 100,
    status: "Available",
    SKU: "FILTER001",
    brand: "ایران خودرو",
    model: "پژو 206",
    categoryId: 2,
    categoryName: "سیستم تعلیق",
    partNumber: "2345-678",
    manufacturer: "Mann",
    warranty: "6 months",
    isOriginal: true,
    rating: 4.2,
    reviewCount: 18,
    imageUrl: "/uploads/products/product_2.jpg",
    additionalImages: ["/uploads/products/product_2_1.jpg"],
    createdAt: "2024-01-05T08:15:00",
    viewCount: 89,
    favoriteCount: 8,
    isFeatured: false,
    isActive: true,
    sku: "FILTER001",
    compatibleCars: "IranKhodro 206, IranKhodro Pars",
    material: "Paper",
    updatedAt: "2024-01-08T11:45:00"
  },
  {
    id: 3,
    name: "روغن موتور 10W40 Chinese Chery",
    description: "روغن موتور با کیفیت بالا برای خودروهای Chinese مدل Chery. این محصول از جنس Synthetic ساخته شده و دارای گارانتی 2 years میباشد.",
    price: 250000,
    discountPrice: 220000,
    stockQuantity: 75,
    status: "Available",
    SKU: "OIL001",
    brand: "چینی",
    model: "چری",
    categoryId: 4,
    categoryName: "موتور و قطعات",
    partNumber: "3456-789",
    manufacturer: "Castrol",
    warranty: "2 years",
    isOriginal: true,
    rating: 4.8,
    reviewCount: 32,
    imageUrl: "/uploads/products/product_3.jpg",
    additionalImages: ["/uploads/products/product_3_1.jpg", "/uploads/products/product_3_2.jpg", "/uploads/products/product_3_3.jpg"],
    createdAt: "2024-01-12T14:20:00",
    viewCount: 210,
    favoriteCount: 25,
    isFeatured: true,
    isActive: true,
    sku: "OIL001",
    compatibleCars: "Chinese Chery, Chinese JAC",
    material: "Synthetic",
    updatedAt: "2024-01-14T16:30:00",
    lastViewedAt: "2024-01-15T10:45:00"
  },
  {
    id: 4,
    name: "باتری 60 آمپر Other Hyundai",
    description: "باتری با کیفیت بالا برای خودروهای Other مدل Hyundai. این محصول از جنس Lead ساخته شده و دارای گارانتی 3 years میباشد.",
    price: 3500000,
    discountPrice: 3200000,
    stockQuantity: 30,
    status: "Available",
    SKU: "BATTERY001",
    brand: "سایر برندها",
    model: "هیوندای",
    categoryId: 3,
    categoryName: "سیستم الکتریکی",
    partNumber: "4567-890",
    manufacturer: "Varta",
    warranty: "3 years",
    isOriginal: true,
    rating: 4.6,
    reviewCount: 45,
    imageUrl: "/uploads/products/product_4.jpg",
    additionalImages: ["/uploads/products/product_4_1.jpg"],
    createdAt: "2024-01-08T09:45:00",
    viewCount: 178,
    favoriteCount: 19,
    isFeatured: true,
    isActive: true,
    sku: "BATTERY001",
    compatibleCars: "Other Hyundai, Other Kia",
    material: "Lead",
    updatedAt: "2024-01-10T13:20:00"
  },
  {
    id: 5,
    name: "شمع پلاتینیومی Saipa Tiba",
    description: "شمع با کیفیت بالا برای خودروهای Saipa مدل Tiba. این محصول از جنس Ceramic ساخته شده و دارای گارانتی 1 year میباشد.",
    price: 120000,
    discountPrice: 95000,
    stockQuantity: 200,
    status: "Available",
    SKU: "SPARK001",
    brand: "سایپا",
    model: "تیبا",
    categoryId: 4,
    categoryName: "موتور و قطعات",
    partNumber: "5678-901",
    manufacturer: "NGK",
    warranty: "1 year",
    isOriginal: true,
    rating: 4.3,
    reviewCount: 28,
    imageUrl: "/uploads/products/product_5.jpg",
    additionalImages: ["/uploads/products/product_5_1.jpg", "/uploads/products/product_5_2.jpg"],
    createdAt: "2024-01-03T11:20:00",
    viewCount: 95,
    favoriteCount: 7,
    isFeatured: false,
    isActive: true,
    sku: "SPARK001",
    compatibleCars: "Saipa Tiba, Saipa Saina",
    material: "Ceramic",
    updatedAt: "2024-01-05T15:40:00"
  },
  {
    id: 6,
    name: "کمربند تایم تسمهای IranKhodro Samand",
    description: "کمربند تایم با کیفیت بالا برای خودروهای IranKhodro مدل Samand. این محصول از جنس Rubber ساخته شده و دارای گارانتی 2 years میباشد.",
    price: 180000,
    discountPrice: 150000,
    stockQuantity: 40,
    status: "Available",
    SKU: "BELT001",
    brand: "ایران خودرو",
    model: "سمند",
    categoryId: 8,
    categoryName: "سیستم انتقال قدرت",
    partNumber: "6789-012",
    manufacturer: "Gates",
    warranty: "2 years",
    isOriginal: true,
    rating: 4.7,
    reviewCount: 36,
    imageUrl: "/uploads/products/product_6.jpg",
    additionalImages: ["/uploads/products/product_6_1.jpg"],
    createdAt: "2024-01-15T13:10:00",
    viewCount: 125,
    favoriteCount: 14,
    isFeatured: true,
    isActive: true,
    sku: "BELT001",
    compatibleCars: "IranKhodro Samand, IranKhodro Dena",
    material: "Rubber",
    updatedAt: "2024-01-16T10:25:00",
    lastViewedAt: "2024-01-16T14:30:00"
  },
  {
    id: 7,
    name: "سنسور اکسیژن Chinese MG",
    description: "سنسور اکسیژن با کیفیت بالا برای خودروهای Chinese مدل MG. این محصول از جنس Metal ساخته شده و دا��ای گارانتی 1 year میباشد.",
    price: 220000,
    discountPrice: 190000,
    stockQuantity: 60,
    status: "Available",
    SKU: "SENSOR001",
    brand: "چینی",
    model: "ام جی",
    categoryId: 7,
    categoryName: "سیستم سوخترسانی",
    partNumber: "7890-123",
    manufacturer: "Bosch",
    warranty: "1 year",
    isOriginal: true,
    rating: 4.4,
    reviewCount: 22,
    imageUrl: "/uploads/products/product_7.jpg",
    additionalImages: ["/uploads/products/product_7_1.jpg", "/uploads/products/product_7_2.jpg"],
    createdAt: "2024-01-07T16:45:00",
    viewCount: 110,
    favoriteCount: 9,
    isFeatured: false,
    isActive: true,
    sku: "SENSOR001",
    compatibleCars: "Chinese MG, Chinese Lifan",
    material: "Metal",
    updatedAt: "2024-01-09T09:30:00"
  },
  {
    id: 8,
    name: "کیت کلاچ کامل Saipa Quick",
    description: "کیت کلاچ با کیفیت بالا برای خودروهای Saipa مدل Quick. این محصول از جنس Composite ساخته شده و دارای گارانتی 3 years میباشد.",
    price: 850000,
    discountPrice: 750000,
    stockQuantity: 25,
    status: "Available",
    SKU: "CLUTCH001",
    brand: "سایپا",
    model: "کوییک",
    categoryId: 8,
    categoryName: "سیستم انتقال قدرت",
    partNumber: "8901-234",
    manufacturer: "Luk",
    warranty: "3 years",
    isOriginal: true,
    rating: 4.9,
    reviewCount: 52,
    imageUrl: "/uploads/products/product_8.jpg",
    additionalImages: ["/uploads/products/product_8_1.jpg", "/uploads/products/product_8_2.jpg", "/uploads/products/product_8_3.jpg"],
    createdAt: "2024-01-11T12:15:00",
    viewCount: 195,
    favoriteCount: 21,
    isFeatured: true,
    isActive: true,
    sku: "CLUTCH001",
    compatibleCars: "Saipa Quick, Saipa Atlas",
    material: "Composite",
    updatedAt: "2024-01-13T14:50:00"
  },
  {
    id: 9,
    name: "دیسک ترمز IranKhodro Dena",
    description: "دیسک ترمز با کیفیت بالا برای خودروهای IranKhodro مدل Dena. این محصول از جنس Steel ساخته شده و دارای گارانتی 2 years میباشد.",
    price: 320000,
    discountPrice: 280000,
    stockQuantity: 35,
    status: "Available",
    SKU: "DISC001",
    brand: "ایران خودرو",
    model: "دنا",
    categoryId: 1,
    categoryName: "سیستم ترمز",
    partNumber: "9012-345",
    manufacturer: "Brembo",
    warranty: "2 years",
    isOriginal: true,
    rating: 4.5,
    reviewCount: 29,
    imageUrl: "/uploads/products/product_9.jpg",
    additionalImages: ["/uploads/products/product_9_1.jpg"],
    createdAt: "2024-01-09T10:30:00",
    viewCount: 142,
    favoriteCount: 16,
    isFeatured: false,
    isActive: true,
    sku: "DISC001",
    compatibleCars: "IranKhodro Dena, IranKhodro Soren",
    material: "Steel",
    updatedAt: "2024-01-11T11:45:00"
  },
  {
    id: 10,
    name: "لوله اگزوز اصلی Other Toyota",
    description: "لوله اگزوز با کیفیت بالا برای خودروهای Other مدل Toyota. این محصول از جنس Aluminum ساخته شده و دارای گارانتی Lifetime میباشد.",
    price: 450000,
    discountPrice: 400000,
    stockQuantity: 20,
    status: "Available",
    SKU: "EXHAUST001",
    brand: "سایر برندها",
    model: "تویوتا",
    categoryId: 6,
    categoryName: "سیستم اگزوز",
    partNumber: "0123-456",
    manufacturer: "Walker",
    warranty: "Lifetime",
    isOriginal: true,
    rating: 4.8,
    reviewCount: 41,
    imageUrl: "/uploads/products/product_10.jpg",
    additionalImages: ["/uploads/products/product_10_1.jpg", "/uploads/products/product_10_2.jpg"],
    createdAt: "2024-01-14T15:20:00",
    viewCount: 168,
    favoriteCount: 18,
    isFeatured: true,
    isActive: true,
    sku: "EXHAUST001",
    compatibleCars: "Other Toyota, Other Mitsubishi",
    material: "Aluminum",
    updatedAt: "2024-01-15T12:10:00",
    lastViewedAt: "2024-01-16T08:45:00"
  }
];

export const searchTestCases = [
  { name: 'لنت ترمز', filters: { search: 'لنت ترمز' } },
  { name: 'فیلتر هوا سایپا', filters: { search: 'فیلتر هوا', carBrand: 'Saipa' } },
  { name: 'روغن موتور چینی', filters: { search: 'روغن موتور', carBrand: 'Chinese' } },
  { name: 'باتری ایران خودرو', filters: { search: 'باتری', carBrand: 'IranKhodro' } },
  { name: 'شمع پلاتینیومی', filters: { search: 'شمع', material: 'Ceramic' } },
  { name: 'محصولات ویژه', filters: { isFeatured: true } },
  { name: 'گارانتی 1 سال', filters: { warranty: '1 year' } },
  { name: 'برند Bosch', filters: { brand: 'Bosch' } },
  { name: 'پراید', filters: { carBrand: 'Saipa', carModel: 'Pride' } },
  { name: 'پژو 206', filters: { carBrand: 'IranKhodro', carModel: '206' } },
];

// آمار محصولات
export const productStats = {
  total: 10,
  byCarBrand: {
    Chinese: 2,
    Saipa: 3,
    IranKhodro: 3,
    Other: 2,
  },
  byMaterial: {
    Metal: 2,
    Paper: 1,
    Synthetic: 1,
    Lead: 1,
    Ceramic: 1,
    Rubber: 1,
    Composite: 1,
    Steel: 1,
    Aluminum: 1,
  },
  featured: 6,
  active: 10,
};

// تگهای محبوب برای جستجو
export const popularTags = [
  'لنت ترمز',
  'فیلتر هوا',
  'روغن موتور',
  'شمع',
  'باتری',
  'کمربند تایم',
  'سنسور اکسیژن',
  'کلاچ',
  'دیسک ترمز',
  'لوله اگزوز',
  'رادیاتور',
  'پمپ آب',
  'دینام',
  'استارت',
  'کمپرسور کولر',
  'لنت کلاچ',
  'سگدست',
  'بلبرینگ',
  'سیبک',
  'طبق',
  'فیلتر روغن',
  'فیلتر سوخت',
  'شمع وایر',
  'کوئل'
];

// هشتگهای محبوب
export const popularHashtags = [
  'قطعات_اصلی',
  'گارانتی_دار',
  'ارسال_سریع',
  'تضمین_کیفیت',
  'پرفروش',
  'جدیدترین',
  'تخفیف_ویژه',
  'اورجینال',
  'سازگار',
  'مقاوم',
  'با_کیفیت',
  'اقتصادی',
  'لوکس',
  'پایدار'
];

// برندهای خودرو
export const carBrands = ['Chinese', 'Saipa', 'IranKhodro', 'Other'];

// مدلهای خودرو
export const carModels = {
  Chinese: ['Chery', 'JAC', 'MG', 'Lifan', 'Changan', 'Geely'],
  Saipa: ['Pride', 'Tiba', 'Saina', 'Quick', 'Atlas', 'Shahin'],
  IranKhodro: ['206', 'Pars', 'Samand', 'Dena', 'Soren', 'Runna'],
  Other: ['Hyundai', 'Kia', 'Toyota', 'Mitsubishi', 'Nissan', 'BMW']
};

// جنسهای قطعات
export const materials = ['Plastic', 'Metal', 'Rubber', 'Ceramic', 'Composite', 'Aluminum', 'Steel', 'Copper', 'Synthetic', 'Paper', 'Lead'];

// گارانتیها
export const warranties = ['6 months', '1 year', '2 years', '3 years', 'Lifetime'];

// دستهبندیها
export const categories = [
  { id: 1, name: 'سیستم ترمز', productCount: 2 },
  { id: 2, name: 'سیستم تعلیق', productCount: 1 },
  { id: 3, name: 'سیستم الکتریکی', productCount: 1 },
  { id: 4, name: 'موتور و قطعات', productCount: 2 },
  { id: 5, name: 'سیستم خنککننده', productCount: 0 },
  { id: 6, name: 'سیستم اگزوز', productCount: 1 },
  { id: 7, name: 'سیستم سوخترسانی', productCount: 1 },
  { id: 8, name: 'سیستم انتقال قدرت', productCount: 2 },
];